### ISSUE TITLE
HSE_VALUE should be defined through config.json or target.json config field

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/cmsis-core-stm32f401xe#7]
Related https://github.com/ARMmbed/mbed-hal-st-stm32f401re/issues/7

Right now the external oscillator frequency value is hardcoded withing the module.
In system_stm32f4xx.c
```C
#if !defined  (HSE_VALUE) 
  #define HSE_VALUE    ((uint32_t)8000000) /*!< Value of the External oscillator in Hz */
#endif /* HSE_VALUE */
```
In our case we use a 16Mhz one, so imho this parameter should be configurable without tinkering with the code.

Also maybe is a good idea to define RCC_OscInitStruct.PLL.PLLM value from HSE_VALUE since it depends on it.

@bcostm could you please have a look?

**Comment by markus-becker-tridonic-com** [comment]
This has been done for the F429, in https://github.com/ARMmbed/cmsis-core-stm32f429xi/blob/master/source/system_stm32f4xx.c#L68. Would be good to have this ported over to F401. Additionally, it would be good to be able to select the internal clock as well in the same way the external can be configured in a config.json.
